### ISSUE TITLE
[Feat] 포메이션 템플릿 기능

### ISSUE THREAD

**Issue by eemdeeks** [DeveloperAcademy-POSTECH/MacC-Team10-Pivoters#17]
## 💡 Issue

여러 포메이션 템플릿을 추가하고 템플릿 선택시 선수 배치 기능을 위한 이슈입니다.

## 📝 Todo
- [x] 포메이션 템플릿 추가
- [x] 포메이션 선택시 템플릿모양으로 선수들 재배치

**Comment by sozohoy** [comment]
대박~~
